language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

services:
  - memcached

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: c5638bb455486cf92c6c3f866be46691b66d1e82b118ad723f32464b2d587ac1
